# Generated by Django 5.0 on 2023-12-11 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('CID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ClassroomName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('EID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('EducatorName', models.CharField(max_length=100)),
                ('InstituteName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('AID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='EID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.educator'),
        ),
    ]
