# Generated by Django 5.0 on 2023-12-12 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='Timestamp',
        ),
        migrations.AddField(
            model_name='assignment',
            name='Deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='UserAssignmentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Results', models.JSONField()),
                ('AID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.assignment')),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.classroom')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserOnlyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Results', models.JSONField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.user')),
            ],
        ),
    ]
