# Generated by Django 5.0 on 2023-12-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apigateway", "0011_alter_assignment_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="Deadline",
            field=models.DateTimeField(default="2023-12-19 17:19:25+0000"),
        ),
    ]
