# Generated by Django 5.0 on 2023-12-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0005_alter_educator_eid'),
        ('apigateway', '0012_alter_assignment_deadline'),
    ]

    operations = [
    ]
