# Generated by Django 5.0 on 2023-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0014_alter_assignment_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='type',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Deadline',
            field=models.DateTimeField(default='2023-12-20 08:25:35+0000'),
        ),
        migrations.AddField(
            model_name='logininfo',
            name='Type',
            field=models.IntegerField(default=0),
        ),
    ]
