# Generated by Django 5.0 on 2023-12-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apigateway", "0014_alter_assignment_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="Deadline",
            field=models.DateTimeField(default="2023-12-20 06:21:35+0000"),
        ),
    ]
