# Generated by Django 5.0 on 2023-12-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0015_alter_assignment_deadline'),
        ('apigateway', '0015_remove_logininfo_type_alter_assignment_deadline_and_more'),
    ]

    operations = [
    ]
