# Generated by Django 5.0 on 2023-12-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0017_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Deadline',
            field=models.DateTimeField(default='2023-12-20 18:11:45+0000'),
        ),
    ]
