# Generated by Django 5.0 on 2023-12-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apigateway", "0017_alter_assignment_deadline_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="Count",
            field=models.IntegerField(default=30),
        ),
    ]
