# Generated by Django 5.0 on 2023-12-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apigateway", "0021_alter_assignment_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="UserName",
            field=models.CharField(max_length=100),
        ),
    ]
